name: JustDiego
favicon: null
layout_spectrum: 0.766741368221119
typography_spectrum: 0.427604406606406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7856844733469188
  lightness: 0.8387756326701492
  saturation: 0.06572374701499939
  rhythmicContrast: 0.15522872749716043
purpose: []
